### ISSUE TITLE
首次加载不显示内容

### ISSUE THREAD

**Issue by 1939323749** [RikaCelery/StudyAtJLU_Desktop#17]
需要切换课程或学期才加载,删除data.db可以复现
1.0.3版本,macOS13.4,jdk18
<img width="797" alt="截屏2023-06-30 15 47 31" src="https://github.com/RikaCelery/StudyAtJLU_Desktop/assets/28222273/57c8a2f2-bc2d-4e0e-bf91-4f521a30d410">

**Comment by RikaCelery** [comment]
你看看 #18

**Comment by 1939323749** [comment]
先合并吧
