### ISSUE TITLE
选择除本学期外的学期报错

### ISSUE THREAD

**Issue by 1939323749** [RikaCelery/StudyAtJLU_Desktop#19]
加载失败,报错退出
<img width="318" alt="截屏2023-06-30 16 04 01" src="https://github.com/RikaCelery/StudyAtJLU_Desktop/assets/28222273/94daabba-fe47-4c20-b0f6-cb0668695a76">

**Comment by 1939323749** [comment]
接口问题?旧版也有这个问题,以前出现过吗🤔

**Comment by RikaCelery** [comment]
🤔

**Comment by RikaCelery** [comment]
以前没有
大概找到问题了
[这里](https://github.com/RikaCelery/StudyAtJLU_Desktop/blob/master/src/jvmMain/kotlin/ui/MainPage.kt#L140-L159)没有加这几个字段

**Comment by RikaCelery** [comment]
fixed at #20
