### ISSUE TITLE
implement cas login

### ISSUE THREAD

**Issue by RikaCelery** [RikaCelery/StudyAtJLU_Desktop#25]
@1939323749 
猜猜我干了什((((

<img width="1470" alt="image" src="https://github.com/RikaCelery/StudyAtJLU_Desktop/assets/94585272/b5960c5c-0170-4523-9904-61a36114f222">

**Comment by 1939323749** [comment]
[jishi](https://github.com/tsurumi-yizhou/JiShi-Android/blob/foss/app/src/main/kotlin/me/yihtseu/jishi/utils/crypto/des.kt)这里有kt版的des.js，实测有用

**Comment by RikaCelery** [comment]
偷了

**Comment by RikaCelery** [comment]
那现在又多了一个python implementation(((((

**Comment by RikaCelery** [comment]
done at 9efc9b5f

@1939323749 我window扔家里了,你要不帮我打个release上去? 🤔

**Comment by 1939323749** [comment]
没有权限，而且好像不能用`packageReleaseMsi`打包

**Comment by RikaCelery** [comment]
😭给你加collaborator可以发吗

packageMsi 好像可以, release就会挂

**Comment by RikaCelery** [comment]
<img width="318" alt="image" src="https://github.com/RikaCelery/StudyAtJLU_Desktop/assets/94585272/2cb2f906-5f6a-4417-8f88-5edd33f12fbc">

你是不是忘了拉更新(

**Comment by 1939323749** [comment]
![image](https://github.com/RikaCelery/StudyAtJLU_Desktop/assets/28222273/8c874090-1b5a-4a09-817b-35aa8f8a570e)
是dev分支吧，应该没错
